server:
  port: 8762
spring:
  application:
    name: nativeconfigserver
  #    表示读取配置文件的方式是本地读取
  profiles:
    active: native
  #    表示本地读取的地址是resources目录下的shared目录
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared